### ISSUE TITLE
Ingress rule for Vidi missing?

### ISSUE THREAD

**Issue by mapcentia** [sashuk/gc2_aks#1]
Should there not be a rule for Vidi?
https://github.com/sashuk/gc2_aks/blob/master/ingress-rules.yaml

**Comment by sashuk** [comment]
@mapcentia Rules were added in https://github.com/sashuk/gc2_aks/blob/master/k8s-configurations/00-ingress-rules-gc2.yaml and https://github.com/sashuk/gc2_aks/blob/master/k8s-configurations/00-ingress-rules-vidi.yaml

Live demo:

https://vidi.eastus.cloudapp.azure.com/app/test/public/#osm/9/39.6063/-7.0429/v:public.point
